#!/bin/zsh

alias ib="cp ~/projects/wolfpackplacesionic/src/app/models/config.deployed ~/projects/wolfpackplacesionic/src/app/models/config.ts; ionic build --prod --release; ionic cap sync;"
alias ibt="cp ~/projects/wolfpackplacesionic/src/app/models/config.testing ~/projects/wolfpackplacesionic/src/app/models/config.ts; ionic build; ionic cap sync;"
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}

export ZSH="$HOME/.oh-my-zsh"

export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
# avdmanager, sdkmanager
export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin

# adb, logcat
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

# emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator

# Location of my dotfiles
DOTFILES=$HOME/.dotfiles

# Update PATH
path=(
    /usr/local/{bin,sbin}
    /bin/sbin
    /sbin
    $DOTFILES/scripts
    $path
)
typeset -U path

ZSH_THEME="powerlevel10k/powerlevel10k"
DEFAULT_USER=eric
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MODE='default'
#POWERLEVEL9K_COLOR_SCHEME='light'
#POWERLEVEL9K_MODE='awesome-fontconfig' #Use with powerline fonts
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir disk_usage  vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

# POWERLEVEL9K_STATUS_OK_BACKGROUND='233'
# POWERLEVEL9K_STATUS_OK_FOREGROUND='084'
# POWERLEVEL9K_STATUS_ERROR_BACKGROUND='233'
# POWERLEVEL9K_STATUS_ERROR_FOREGROUND='196'
# POWERLEVEL9K_NODE_VERSION_BACKGROUND='63'
# POWERLEVEL9K_TIME_BACKGROUND='233'
# POWERLEVEL9K_TIME_FOREGROUND='084'


plugins=(brew colored-man-pages git git-extras gitignore node npm
        macos pip python sudo urltools web-search fasd command-not-found
	      postgres history-substring-search cp zsh-syntax-highlighting
        zsh-autosuggestions)

alias zshconfig="mate ~/.zshrc"
alias sssh="ssh 192.168.40.55"

brew-essentials() {
  brew install autojump
  brew install cloc
  brew install cmake
  brew install coreutils
  brew install ctags
  brew install progress
  brew install git
  brew install httpie
  brew install icdiff
  brew install lnav
  brew install ncdu
  brew install p7zip
  brew install pstree
  brew install the_silver_searcher
  brew install vim
  brew tap homebrew/cask-fonts
  brew install --cask font-jetbrains-mono
  brew isntall fasd
  brew install watch
  brew install zsh
}

# additional configuration for zsh
# Remove the history (fc -l) command from the history list when invoked.
setopt histnostore
# Remove superfluous blanks from each command line being added to the history list.
setopt histreduceblanks
# Do not exit on end-of-file. Require the use of exit or logout instead.
setopt ignoreeof
# Print the exit value of programs with non-zero exit status.
setopt printexitvalue
# Do not share history
setopt no_share_history

# if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# change the size of history files
export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;

# Shell
export CLICOLOR=1
export EDITOR='vim'
export PAGER='less'

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

source $ZSH/oh-my-zsh.sh


# Load Angular CLI autocompletion.
source <(ng completion script)
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
eval "$(zoxide init zsh)"

# Enable vi mode
bindkey -v
export KEYTIMEOUT=1
# Enable vi mode
bindkey -v
export KEYTIMEOUT=1

# Change cursor shape depending on mode
function zle-keymap-select {
  if [[ $KEYMAP == vicmd ]]; then
    # NORMAL mode → block cursor
    echo -ne '\e[2 q'
  else
    # INSERT mode → beam (bar) cursor
    echo -ne '\e[6 q'
  fi
  zle reset-prompt
}
zle -N zle-keymap-select

# Set cursor shape on shell start
function zle-line-init {
  echo -ne '\e[6 q'   # start in INSERT mode (beam)
}
zle -N zle-line-init

# Restore cursor on exit
function reset-cursor {
  echo -ne '\e[6 q'
}
precmd_functions+=(reset-cursor)
